// Datos turísticos globales con estadísticas de visitantes
const datosTurismo = [
    {
        pais: "España",
        region: "Europa Occidental",
        capital: "Madrid",
        visitantes_anuales_millones: 83.5,
        temporada_alta: "Verano",
        idioma_principal: "Español",
        moneda: "Euro",
        gasto_promedio_diario: 145,
        dias_estancia_promedio: 8.5,
        principal_atractivo: "Playas y Arte",
        poblacion_millones: 47.4,
        superficie_km2: 505990,
        indice_seguridad: 8.2,
        clima_predominante: "Mediterráneo",
        patrimonio_unesco: 49,
        aeropuertos_internacionales: 28,
        conectividad_internet: "Excelente",
        tipo_turismo: "Cultural y de Playa",
        estacion_preferida: "Primavera-Verano",
        rating_destino: 9.1
    },
    {
        pais: "Francia",
        region: "Europa Occidental",
        capital: "París",
        visitantes_anuales_millones: 89.4,
        temporada_alta: "Verano",
        idioma_principal: "Francés",
        moneda: "Euro",
        gasto_promedio_diario: 165,
        dias_estancia_promedio: 7.2,
        principal_atractivo: "Arte y Gastronomía",
        poblacion_millones: 67.8,
        superficie_km2: 643801,
        indice_seguridad: 7.8,
        clima_predominante: "Templado",
        patrimonio_unesco: 45,
        aeropuertos_internacionales: 25,
        conectividad_internet: "Excelente",
        tipo_turismo: "Cultural",
        estacion_preferida: "Primavera",
        rating_destino: 9.3
    },
    {
        pais: "Italia",
        region: "Europa Meridional",
        capital: "Roma",
        visitantes_anuales_millones: 64.5,
        temporada_alta: "Verano",
        idioma_principal: "Italiano",
        moneda: "Euro",
        gasto_promedio_diario: 155,
        dias_estancia_promedio: 9.1,
        principal_atractivo: "Historia y Arte",
        poblacion_millones: 59.1,
        superficie_km2: 301340,
        indice_seguridad: 7.9,
        clima_predominante: "Mediterráneo",
        patrimonio_unesco: 58,
        aeropuertos_internacionales: 22,
        conectividad_internet: "Muy Buena",
        tipo_turismo: "Cultural e Histórico",
        estacion_preferida: "Primavera-Verano",
        rating_destino: 9.0
    },
    {
        pais: "Estados Unidos",
        region: "América del Norte",
        capital: "Washington D.C.",
        visitantes_anuales_millones: 79.3,
        temporada_alta: "Verano",
        idioma_principal: "Inglés",
        moneda: "Dólar USD",
        gasto_promedio_diario: 185,
        dias_estancia_promedio: 10.5,
        principal_atractivo: "Diversidad y Entretenimiento",
        poblacion_millones: 331.9,
        superficie_km2: 9833517,
        indice_seguridad: 7.5,
        clima_predominante: "Variado",
        patrimonio_unesco: 24,
        aeropuertos_internacionales: 45,
        conectividad_internet: "Excelente",
        tipo_turismo: "Entretenimiento y Naturaleza",
        estacion_preferida: "Primavera-Verano",
        rating_destino: 8.8
    },
    {
        pais: "Reino Unido",
        region: "Europa Occidental",
        capital: "Londres",
        visitantes_anuales_millones: 37.7,
        temporada_alta: "Verano",
        idioma_principal: "Inglés",
        moneda: "Libra Esterlina",
        gasto_promedio_diario: 175,
        dias_estancia_promedio: 6.8,
        principal_atractivo: "Historia y Cultura",
        poblacion_millones: 67.3,
        superficie_km2: 242495,
        indice_seguridad: 8.1,
        clima_predominante: "Oceánico",
        patrimonio_unesco: 33,
        aeropuertos_internacionales: 18,
        conectividad_internet: "Excelente",
        tipo_turismo: "Cultural",
        estacion_preferida: "Verano",
        rating_destino: 8.9
    },
    {
        pais: "Tailandia",
        region: "Sudeste Asiático",
        capital: "Bangkok",
        visitantes_anuales_millones: 40.1,
        temporada_alta: "Invierno",
        idioma_principal: "Tailandés",
        moneda: "Baht",
        gasto_promedio_diario: 85,
        dias_estancia_promedio: 12.3,
        principal_atractivo: "Playas y Templos",
        poblacion_millones: 70.0,
        superficie_km2: 513120,
        indice_seguridad: 7.2,
        clima_predominante: "Tropical",
        patrimonio_unesco: 6,
        aeropuertos_internacionales: 8,
        conectividad_internet: "Buena",
        tipo_turismo: "Tropical y Cultural",
        estacion_preferida: "Invierno",
        rating_destino: 8.7
    },
    {
        pais: "Japón",
        region: "Asia Oriental",
        capital: "Tokio",
        visitantes_anuales_millones: 31.9,
        temporada_alta: "Primavera",
        idioma_principal: "Japonés",
        moneda: "Yen",
        gasto_promedio_diario: 195,
        dias_estancia_promedio: 8.8,
        principal_atractivo: "Cultura y Tecnología",
        poblacion_millones: 125.8,
        superficie_km2: 377915,
        indice_seguridad: 9.2,
        clima_predominante: "Templado",
        patrimonio_unesco: 25,
        aeropuertos_internacionales: 15,
        conectividad_internet: "Excelente",
        tipo_turismo: "Cultural y Tecnológico",
        estacion_preferida: "Primavera-Otoño",
        rating_destino: 9.2
    },
    {
        pais: "Alemania",
        region: "Europa Central",
        capital: "Berlín",
        visitantes_anuales_millones: 39.8,
        temporada_alta: "Verano",
        idioma_principal: "Alemán",
        moneda: "Euro",
        gasto_promedio_diario: 135,
        dias_estancia_promedio: 7.5,
        principal_atractivo: "Historia y Arquitectura",
        poblacion_millones: 83.2,
        superficie_km2: 357022,
        indice_seguridad: 8.5,
        clima_predominante: "Templado",
        patrimonio_unesco: 51,
        aeropuertos_internacionales: 16,
        conectividad_internet: "Excelente",
        tipo_turismo: "Cultural e Histórico",
        estacion_preferida: "Primavera-Verano",
        rating_destino: 8.6
    },
    {
        pais: "México",
        region: "América del Norte",
        capital: "Ciudad de México",
        visitantes_anuales_millones: 45.0,
        temporada_alta: "Invierno",
        idioma_principal: "Español",
        moneda: "Peso Mexicano",
        gasto_promedio_diario: 95,
        dias_estancia_promedio: 9.7,
        principal_atractivo: "Playas y Cultura",
        poblacion_millones: 128.9,
        superficie_km2: 1964375,
        indice_seguridad: 6.8,
        clima_predominante: "Variado",
        patrimonio_unesco: 35,
        aeropuertos_internacionales: 12,
        conectividad_internet: "Buena",
        tipo_turismo: "De Playa y Cultural",
        estacion_preferida: "Invierno",
        rating_destino: 8.4
    },
    {
        pais: "Australia",
        region: "Oceanía",
        capital: "Canberra",
        visitantes_anuales_millones: 9.5,
        temporada_alta: "Verano",
        idioma_principal: "Inglés",
        moneda: "Dólar Australiano",
        gasto_promedio_diario: 165,
        dias_estancia_promedio: 15.2,
        principal_atractivo: "Naturaleza y Vida Salvaje",
        poblacion_millones: 25.7,
        superficie_km2: 7692024,
        indice_seguridad: 8.7,
        clima_predominante: "Variado",
        patrimonio_unesco: 20,
        aeropuertos_internacionales: 9,
        conectividad_internet: "Excelente",
        tipo_turismo: "Naturaleza y Aventura",
        estacion_preferida: "Primavera-Verano",
        rating_destino: 8.9
    },
    {
        pais: "Brasil",
        region: "América del Sur",
        capital: "Brasília",
        visitantes_anuales_millones: 6.6,
        temporada_alta: "Invierno",
        idioma_principal: "Portugués",
        moneda: "Real Brasileño",
        gasto_promedio_diario: 75,
        dias_estancia_promedio: 11.4,
        principal_atractivo: "Playas y Naturaleza",
        poblacion_millones: 215.3,
        superficie_km2: 8515767,
        indice_seguridad: 6.2,
        clima_predominante: "Tropical",
        patrimonio_unesco: 23,
        aeropuertos_internacionales: 11,
        conectividad_internet: "Buena",
        tipo_turismo: "De Playa y Ecológico",
        estacion_preferida: "Invierno",
        rating_destino: 8.1
    },
    {
        pais: "India",
        region: "Asia Meridional",
        capital: "Nueva Delhi",
        visitantes_anuales_millones: 17.9,
        temporada_alta: "Invierno",
        idioma_principal: "Hindi",
        moneda: "Rupia India",
        gasto_promedio_diario: 45,
        dias_estancia_promedio: 14.6,
        principal_atractivo: "Cultura y Espiritualidad",
        poblacion_millones: 1380.0,
        superficie_km2: 3287263,
        indice_seguridad: 6.5,
        clima_predominante: "Tropical",
        patrimonio_unesco: 40,
        aeropuertos_internacionales: 23,
        conectividad_internet: "Regular",
        tipo_turismo: "Cultural y Espiritual",
        estacion_preferida: "Invierno",
        rating_destino: 7.9
    },
    {
        pais: "Grecia",
        region: "Europa Meridional",
        capital: "Atenas",
        visitantes_anuales_millones: 33.1,
        temporada_alta: "Verano",
        idioma_principal: "Griego",
        moneda: "Euro",
        gasto_promedio_diario: 125,
        dias_estancia_promedio: 8.9,
        principal_atractivo: "Historia y Islas",
        poblacion_millones: 10.7,
        superficie_km2: 131957,
        indice_seguridad: 7.9,
        clima_predominante: "Mediterráneo",
        patrimonio_unesco: 18,
        aeropuertos_internacionales: 7,
        conectividad_internet: "Muy Buena",
        tipo_turismo: "Histórico y de Islas",
        estacion_preferida: "Primavera-Verano",
        rating_destino: 8.8
    },
    {
        pais: "Turquía",
        region: "Asia Occidental",
        capital: "Ankara",
        visitantes_anuales_millones: 51.2,
        temporada_alta: "Verano",
        idioma_principal: "Turco",
        moneda: "Lira Turca",
        gasto_promedio_diario: 85,
        dias_estancia_promedio: 9.3,
        principal_atractivo: "Historia y Cultura",
        poblacion_millones: 84.3,
        superficie_km2: 783562,
        indice_seguridad: 6.9,
        clima_predominante: "Mediterráneo",
        patrimonio_unesco: 19,
        aeropuertos_internacionales: 12,
        conectividad_internet: "Buena",
        tipo_turismo: "Cultural e Histórico",
        estacion_preferida: "Primavera-Verano",
        rating_destino: 8.3
    },
    {
        pais: "Canadá",
        region: "América del Norte",
        capital: "Ottawa",
        visitantes_anuales_millones: 22.1,
        temporada_alta: "Verano",
        idioma_principal: "Inglés/Francés",
        moneda: "Dólar Canadiense",
        gasto_promedio_diario: 145,
        dias_estancia_promedio: 8.7,
        principal_atractivo: "Naturaleza y Paisajes",
        poblacion_millones: 38.2,
        superficie_km2: 9984670,
        indice_seguridad: 9.1,
        clima_predominante: "Continental",
        patrimonio_unesco: 20,
        aeropuertos_internacionales: 13,
        conectividad_internet: "Excelente",
        tipo_turismo: "Naturaleza y Aventura",
        estacion_preferida: "Verano",
        rating_destino: 8.9
    }
];