// Datos de puntuaciones de videojuegos con información detallada
const datosGaming = [
    {
        jugador: "ProGamer_2024",
        juego: "Call of Duty",
        nivel: "Veterano",
        puntuacion: 127500,
        tiempo_jugado_horas: 245,
        kills: 1850,
        deaths: 420,
        ratio_kd: 4.40,
        partidas_jugadas: 312,
        partidas_ganadas: 287,
        porcentaje_victorias: 92,
        plataforma: "PC",
        region: "Europa",
        fecha_registro: "2024-01-15",
        rango: "Leyenda",
        experiencia_total: 45000,
        arma_favorita: "AK-47",
        modo_favorito: "Battle Royale",
        clan: "Elite Warriors",
        logros_desbloqueados: 48,
        horas_semanales: 35
    },
    {
        jugador: "MasterChief_87",
        juego: "Halo Infinite",
        nivel: "Onyx",
        puntuacion: 98750,
        tiempo_jugado_horas: 189,
        kills: 1456,
        deaths: 389,
        ratio_kd: 3.74,
        partidas_jugadas: 267,
        partidas_ganadas: 201,
        porcentaje_victorias: 75,
        plataforma: "Xbox",
        region: "América del Norte",
        fecha_registro: "2024-02-03",
        rango: "Diamante",
        experiencia_total: 38500,
        arma_favorita: "Battle Rifle",
        modo_favorito: "Arena",
        clan: "Spartan Force",
        logros_desbloqueados: 42,
        horas_semanales: 28
    },
    {
        jugador: "NinjaStrike",
        juego: "Valorant",
        nivel: "Radiante",
        puntuacion: 156300,
        tiempo_jugado_horas: 334,
        kills: 2145,
        deaths: 578,
        ratio_kd: 3.71,
        partidas_jugadas: 445,
        partidas_ganadas: 378,
        porcentaje_victorias: 85,
        plataforma: "PC",
        region: "Asia",
        fecha_registro: "2023-11-20",
        rango: "Radiante",
        experiencia_total: 52000,
        arma_favorita: "Vandal",
        modo_favorito: "Competitivo",
        clan: "Phantom Gaming",
        logros_desbloqueados: 56,
        horas_semanales: 42
    },
    {
        jugador: "RocketQueen",
        juego: "Rocket League",
        nivel: "Gran Campeón",
        puntuacion: 89400,
        tiempo_jugado_horas: 156,
        kills: 0,
        deaths: 0,
        ratio_kd: 0,
        partidas_jugadas: 234,
        partidas_ganadas: 189,
        porcentaje_victorias: 81,
        plataforma: "PlayStation",
        region: "América del Sur",
        fecha_registro: "2024-03-10",
        rango: "Gran Campeón II",
        experiencia_total: 29500,
        arma_favorita: "N/A",
        modo_favorito: "Ranked 3v3",
        clan: "Supersonic Legends",
        logros_desbloqueados: 38,
        horas_semanales: 22
    },
    {
        jugador: "FortniteKing",
        juego: "Fortnite",
        nivel: "Champion",
        puntuacion: 143700,
        tiempo_jugado_horas: 278,
        kills: 1789,
        deaths: 445,
        ratio_kd: 4.02,
        partidas_jugadas: 356,
        partidas_ganadas: 298,
        porcentaje_victorias: 84,
        plataforma: "PC",
        region: "Europa",
        fecha_registro: "2024-01-05",
        rango: "Champion League",
        experiencia_total: 47500,
        arma_favorita: "SCAR",
        modo_favorito: "Battle Royale Solo",
        clan: "Victory Royale",
        logros_desbloqueados: 51,
        horas_semanales: 38
    },
    {
        jugador: "ApexPredator",
        juego: "Apex Legends",
        nivel: "Predador",
        puntuacion: 134500,
        tiempo_jugado_horas: 267,
        kills: 1934,
        deaths: 467,
        ratio_kd: 4.14,
        partidas_jugadas: 389,
        partidas_ganadas: 312,
        porcentaje_victorias: 80,
        plataforma: "PC",
        region: "América del Norte",
        fecha_registro: "2023-12-15",
        rango: "Predador",
        experiencia_total: 44000,
        arma_favorita: "R-301 Carbine",
        modo_favorito: "Ranked",
        clan: "Legends Squad",
        logros_desbloqueados: 49,
        horas_semanales: 35
    },
    {
        jugador: "OverwatchHero",
        juego: "Overwatch 2",
        nivel: "Maestro",
        puntuacion: 92800,
        tiempo_jugado_horas: 198,
        kills: 1567,
        deaths: 423,
        ratio_kd: 3.70,
        partidas_jugadas: 278,
        partidas_ganadas: 223,
        porcentaje_victorias: 80,
        plataforma: "PC",
        region: "Europa",
        fecha_registro: "2024-02-20",
        rango: "Maestro",
        experiencia_total: 35500,
        arma_favorita: "N/A",
        modo_favorito: "Competitivo",
        clan: "Heroes United",
        logros_desbloqueados: 43,
        horas_semanales: 30
    },
    {
        jugador: "LeagueOfLegend",
        juego: "League of Legends",
        nivel: "Challenger",
        puntuacion: 167200,
        tiempo_jugado_horas: 389,
        kills: 2345,
        deaths: 567,
        ratio_kd: 4.14,
        partidas_jugadas: 456,
        partidas_ganadas: 398,
        porcentaje_victorias: 87,
        plataforma: "PC",
        region: "Asia",
        fecha_registro: "2023-10-08",
        rango: "Challenger",
        experiencia_total: 58500,
        arma_favorita: "N/A",
        modo_favorito: "Ranked Solo",
        clan: "Challenger Elite",
        logros_desbloqueados: 62,
        horas_semanales: 45
    },
    {
        jugador: "CSGOPro",
        juego: "Counter-Strike 2",
        nivel: "Global Elite",
        puntuacion: 145600,
        tiempo_jugado_horas: 312,
        kills: 2103,
        deaths: 534,
        ratio_kd: 3.94,
        partidas_jugadas: 387,
        partidas_ganadas: 334,
        porcentaje_victorias: 86,
        plataforma: "PC",
        region: "Europa",
        fecha_registro: "2023-09-12",
        rango: "Global Elite",
        experiencia_total: 49500,
        arma_favorita: "AK-47",
        modo_favorito: "Competitivo",
        clan: "Global Gaming",
        logros_desbloqueados: 54,
        horas_semanales: 40
    },
    {
        jugador: "MinecraftBuilder",
        juego: "Minecraft",
        nivel: "Master Builder",
        puntuacion: 78500,
        tiempo_jugado_horas: 445,
        kills: 234,
        deaths: 89,
        ratio_kd: 2.63,
        partidas_jugadas: 156,
        partidas_ganadas: 134,
        porcentaje_victorias: 86,
        plataforma: "PC",
        region: "América del Norte",
        fecha_registro: "2024-01-30",
        rango: "Master Builder",
        experiencia_total: 67000,
        arma_favorita: "Diamond Sword",
        modo_favorito: "Survival",
        clan: "Creative Masters",
        logros_desbloqueados: 71,
        horas_semanales: 25
    },
    {
        jugador: "FIFAChampion",
        juego: "FIFA 24",
        nivel: "División 1",
        puntuacion: 94300,
        tiempo_jugado_horas: 167,
        kills: 0,
        deaths: 0,
        ratio_kd: 0,
        partidas_jugadas: 289,
        partidas_ganadas: 234,
        porcentaje_victorias: 81,
        plataforma: "PlayStation",
        region: "Europa",
        fecha_registro: "2024-04-01",
        rango: "División 1",
        experiencia_total: 31000,
        arma_favorita: "N/A",
        modo_favorito: "Ultimate Team",
        clan: "Football Legends",
        logros_desbloqueados: 45,
        horas_semanales: 20
    },
    {
        jugador: "WoWGuildMaster",
        juego: "World of Warcraft",
        nivel: "80",
        puntuacion: 156700,
        tiempo_jugado_horas: 567,
        kills: 1456,
        deaths: 234,
        ratio_kd: 6.22,
        partidas_jugadas: 234,
        partidas_ganadas: 198,
        porcentaje_victorias: 85,
        plataforma: "PC",
        region: "América del Norte",
        fecha_registro: "2023-08-15",
        rango: "Guild Master",
        experiencia_total: 89500,
        arma_favorita: "Legendary Staff",
        modo_favorito: "Mythic Raids",
        clan: "Dragon Slayers",
        logros_desbloqueados: 134,
        horas_semanales: 50
    }
];